### ISSUE TITLE
CopyToClipboard test error (documentation site)

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#276]
### Issue description
Running tests causes an error on CopyToClipboard. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Run `yarn test`

### What's the expected result?
- No error

### What's the actual result?
- Full error:

```
Warning: An update to CopyToClipboard inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at CopyToClipboard (/Users/tharpol/code/ncids/docs/src/components/CopyToClipboard.jsx:6:28)

      10 |              if (!copied) return;
      11 |              const timeout = setTimeout(() => {
    > 12 |                      setCopied(false);
         |                      ^
      13 |              }, 1000);
      14 |
      15 |              return () => clearTimeout(timeout);

      at printWarning (../node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (../node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (../node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at setCopied (../node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at src/components/CopyToClipboard.jsx:12:4
      at callback (../node_modules/@jest/fake-timers/build/legacyFakeTimers.js:565:32)
      at FakeTimers._runTimerHandle (../node_modules/@jest/fake-timers/build/legacyFakeTimers.js:601:9)
      at FakeTimers.runAllTimers (../node_modules/@jest/fake-timers/build/legacyFakeTimers.js:205:12)
```

### Additional details / screenshot
![Screen Shot 2021-11-18 at 8 40 44 AM](https://user-images.githubusercontent.com/85901679/142436457-9a42e083-1bf4-4d19-8198-4d4f0ebe5ecc.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Closing this ticket as it is no longer an issue.
